var products = [  
    {    
        "id":1,
        "name": "Girls Buckle Decor Flats, Glamorous Party Glitter Mary Jane Flats",    
        "price": 28.60,    
        "description": "Multicolor, Round Toe for Girls with Glitter upper material",
        "category":"kids",
        "rating": 4,
        "label": 'new',    
        "labelText": "100% New",
        "delivery": 5.00,
        "newcollection":1,
        "images" : {
            1 : "img/product/kids/shoes-1.png",
            2 : "img/product/kids/shoes-2.png",
            3 : "img/product/kids/shoes-3.png",
            4 : "img/product/kids/shoes-4.png",
        }
    },  
    {    
        "id":2,
        "name": "Newborn Baby Letter Graphic Tee & Floral Print Pants",    
        "price": 17.99,    
        "description": "Multicolored casual Tee Pants with V neck and long sleeve for girls with medium stretch. Machine wash, do not dry clean.",
        "category":"kids",
        "rating": 5,  
        "label": 'stockout',     
        "labelText": "Out of Stock",
        "delivery": "Free delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/kids/kids-9.png",
            2 : "img/product/kids/kids-10.png",
            3 : "img/product/kids/kids-11.png",
            4 : "img/product/kids/kids-12.png",
        }   
    },  
    {    
        "id":3,
        "name": "SHEIN Men Solid Blazer & Suit Pants Set",    
        "price": 99.99,    
        "description": "Dusty Pink plain work with woven fabric blazer. 100% plyester pants & tops composition with non-stretchable regular fit. Machine wash or professinal dry.",
        "category":"men",
        "image" : "img/product/p-11.jpeg",
        "rating": 5,  
        "label": 'new',    
        "labelText": "New",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/mens/mens-1.png",
            2 : "img/product/mens/mens-2.png",
            3 : "img/product/mens/mens-3.png",
            4 : "img/product/mens/mens-5.png",
        }     
    },
    {    
        "id":4,
        "name": "Nike Boys White & Yellow Brand Logo Printed T-Shirt",    
        "price": 18.60,    
        "description": "white and yellow Tshirt for boys of cotton fabric with rounded neck and  regular length",
        "category":"kids",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/kids/kids-5.png",
            2 : "img/product/kids/kids-6.png",
            3 : "img/product/kids/kids-7.png",
            4 : "img/product/kids/kids-8.png",
        }
    },
    {    
        "id":5,
        "name": "Fashion Dram Girls Top & Sweat Pants",    
        "price": 28.60,    
        "description": "1 Top and 1 Sweatpant for 5 to 6 years girls with soft and quality material.",
        "category":"kids",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/kids/kids-16.png",
            2 : "img/product/kids/kids-18.png",
            3 : "img/product/kids/kids-17.png",
            4 : "img/product/kids/kids-19.png",
        }
    },
    {    
        "id":6,
        "name": "Men Olive Green Solid Active Bomber Jacket",    
        "price": 35.00,    
        "description": "Full front open zipper with full sleeves of regular fit for mens. Lightweight jacket provides insulation and helps maintain body temperature in mild cold. Breathable fabric helps sweat dry gast. Zippered pockets keep your essentials safe.",
        "category":"men",
        "rating": 4,

        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/mens/mens-13.png",
            2 : "img/product/mens/mens-14.png",
            3 : "img/product/mens/mens-15.png",
            4 : "img/product/mens/mens-16.png",
            5 : "img/product/mens/mens-17.png",
        }
    },
    {    
        "id":7,
        "name": "Train Icons 3-Bar Logo Training T-Shirt",    
        "price": 20.35,    
        "description": "White and pink training T-Shirt for men with round neck regular length and short regular sleeves of knitted polyster fabric.",
        "category":"men",
        "rating": 4,
        "label": 'sale',    
        "labelText": "Sale",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/mens/mens-18.png",
            2 : "img/product/mens/mens-19.png",
            3 : "img/product/mens/mens-20.png",
            4 : "img/product/mens/mens-21.png",
        }
    },
    {    
        "id":8,
        "name": "Navy Blue Colourblocked Layered Satin Dress",    
        "price": 30.35,    
        "description": "Beautify navy blue colourblocked fit and flare dress, round neck with short flutter sleeve till knee length in concealed zip closure. Dry clean only",
        "category":"kids",
        "rating": 5,
        "label": 'new',    
        "labelText": "New Release",
        "delivery": 5.00,
        "newcollection":1,
        "images" : {
            1 : "img/product/kids/kids-1.png",
            2 : "img/product/kids/kids-2.png",
            3 : "img/product/kids/kids-3.png",
            4 : "img/product/kids/kids-4.png",
        }
    },
    {    
        "id":9,
        "name": "Gunmetal-Toned Striped Saree",    
        "price": 30.35,    
        "description": "Beautify navy blue colourblocked fit and flare dress, round neck with short flutter sleeve till knee length in concealed zip closure. Dry clean only",
        "category":"women",
        "rating": 5,
        "label": 'new',    
        "labelText": "New Release",
        "delivery": 5.00,
        "newcollection":1,
        "images" : {
            1 : "img/product/womens/saree-4.jpg",
            2 : "img/product/womens/saree-5.jpg",
            3 : "img/product/womens/saree-6.png",
        }
    },
    {    
        "id":10,
        "name": "Fashion casual solid purple top for women",    
        "price": 17.35,    
        "description": "Purple colored solid regular sleeves for womens of cotton blend fabric.",
        "category":"women",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": 3.00,
        "newcollection":0,
        "images" : {
            1 : "img/product/womens/fashion-1.png",
            2 : "img/product/womens/fashion-2.png",
            3 : "img/product/womens/fashion-3.png",
            3 : "img/product/womens/fashion-4.png",
        }
    },
    {    
        "id":11,
        "name": "Women-gown silver dress",    
        "price": 20.35,    
        "description": "Gown type silver western wear. Knee length polyester embellished pattern for women",
        "category":"women",
        "rating": 2,
        "label": '',    
        "labelText": "",
        "delivery": 2.05,
        "newcollection":0,
        "images" : {
            1 : "img/product/womens/silver-1.png",
            2 : "img/product/womens/silver-2.png",
            3 : "img/product/womens/silver-3.png",
            3 : "img/product/womens/silver-4.png",
        }
    },
    {    
        "id":12,
        "name": "Surhi women printed straight kurta",    
        "price": 15.00,    
        "description": "White kurta casual wear for girls. Knee length pure cotton printed pattern with round neck, knee length.",
        "category":"women",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": "Free delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/womens/kurta-1.png",
            2 : "img/product/womens/kurta-2.png",
            3 : "img/product/womens/kurta-3.png",
        }
    },
    {    
        "id":13,
        "name": "Women Black Leather Structured Handheld Bag",    
        "price": 15.00,    
        "description": "Black solid Leather handheld bag with 1 main compartment, has a zip closure with table sleeve, two handles with a non-detachable sling strap. Wipe with a clean, dry cloth when needed.",
        "category":"accessories",
        "rating": 3,
        "label": 'new',    
        "labelText": "New Release",
        "delivery": 4.15,
        "newcollection":1,
        "images" : {
            1 : "img/product/accessories/handbag-6.png",
            2 : "img/product/accessories/handbag-9.png",
            3 : "img/product/accessories/handbag-8.png",
            4 : "img/product/accessories/handbag-7.png",
        }
    },
    {    
        "id":14,
        "name": "Brown Solid Leather Handheld Bag",    
        "price": 15.00,    
        "description": "Brown solid handheld bag, has a zip closure 3 main compartments, 3 inner pockets with two handles witha a detachable sling strap. Coupon Discount: 20% off. Applicable on orders above $100. Coupon code: BeStylish@1",
        "category":"accessories",
        "rating": 3,
        "label": 'stockout',    
        "labelText": "Out of Stock",
        "delivery": 4.15,
        "newcollection":1,
        "images" : {
            1 : "img/product/accessories/handbag-1.png",
            2 : "img/product/accessories/handbag-2.png",
            3 : "img/product/accessories/handbag-3.png",
            4 : "img/product/accessories/handbag-4.png",
            5 : "img/product/accessories/handbag-5.png",
        }
    },
    {    
        "id":15,
        "name": "Trussardi perfume",    
        "price": 25.00,    
        "description": "Le Vie di Milano Musc Noir Enhancer EDP is a type of Eau de Parfum fragrance with a strong and woody scent. It has a formulation of spray and contains top notes of oriental scent, middle notes of fruity fragrance, and bottom notes of woody aroma. This fragrance is designed to be spritzed onto pulse points and should be kept away from direct sunlight. It is recommended not to apply on broken skin. The product is categorized as a regular fragrance and is not labeled as sustainable. It comes in a 100ml bottle.",
        "category":"accessories",
        "rating": 3,
        "label": 'new',    
        "labelText": "New Release",
        "delivery": 4.15,
        "newcollection":1,
        "images" : {
            1 : "img/product/accessories/perfume.png",
            2 : "img/product/accessories/perfume-1.png",
            3 : "img/product/accessories/perfume-2.png",
            4 : "img/product/accessories/handbag-3.png",
        }
    },
    {    
        "id":16,
        "name": "1pc men round pointer quartz watch & 1pc bracelet",    
        "price": 6.20,    
        "description": "This is a men's watch set featuring a quartz movement and a round-shaped rose gold dial. The case material is made of zinc alloy and the strap is made of the same material for a uniform look. The watch also features a calendar function for added convenience. The watch set does not come with a box included. The watch is not waterproof and should not be exposed to water. The watch face is made of a specular material that is not specified. The watch's elegant and classic design makes it suitable for formal or dressy occasions.",
        "category":"accessories",
        "rating": 3,
        "label": '',    
        "labelText": "New Release",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/accessories/watch-1.png",
            2 : "img/product/accessories/watch-2.png",
            3 : "img/product/accessories/watch-3.png",
            4 : "img/product/accessories/watch-2.png",

        }
    },
    {    
        "id":17,
        "name": "1pc men accessories plain baseball cap",    
        "price": 4.60,    
        "description": "This item is a black baseball cap with a casual style, featuring a plain design with no additional patterns or decorations. It is made from fabric, specifically 100% polyester, which is lightweight and durable. The black color and plain design make this baseball cap versatile and easy to pair with a range of outfits. It is suitable for casual occasions and can be worn for various outdoor activities. The fabric material is easy to clean and maintain, ensuring its longevity and usefulness in any wardrobe. The cap is designed to fit most head sizes comfortably and securely, making it a practical and stylish accessory for anyone looking to add a classic touch to their look.",
        "category":"accessories",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/cap-1.png",
            2 : "img/product/accessories/cap-2.png",
            3 : "img/product/accessories/cap-3.png",
            4 : "img/product/accessories/cap-4.png",
        }
    },
    {    
        "id":18,
        "name": "2pcs men minimalist chain necklace",    
        "price": 3.60,    
        "description": "This item is a multicolor accessory with a fashionable style, designed for men. It is made from stainless steel, a durable and corrosion-resistant material. The multicolor design adds a unique and eye-catching touch to any outfit. The accessory does not feature any magnetic components, making it safe to wear around electronic devices. Its fashionable style makes it suitable for various occasions, from casual outings to formal events. The stainless steel material is easy to clean and maintain, ensuring its longevity and usefulness in any wardrobe. Overall, this accessory is a stylish and practical addition to any fashion-forward man's collection.",
        "category":"accessories",
        "rating": 5,
        "label": 'sale',    
        "labelText": "Sale",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/accessories/chainNecklace-1.png",
            2 : "img/product/accessories/chainNecklace-2.png",
            3 : "img/product/accessories/chainNecklace-3.png",
        }
    },
    {    
        "id":19,
        "name": "Men Rectangle Pendant Necklace",    
        "price": 2.00,    
        "description": "This is a fashionable black-colored accessory, most likely a piece of jewelry or an accessory for clothing. It is designed for men and is not magnetic. The design of the accessory features geometric details, which add to its stylish appearance. The material used to make this accessory is iron, which is known for its durability and strength.",
        "category":"accessories",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/pendentNecklace-1.png",
            2 : "img/product/accessories/pendentNecklace-2.png",
            3 : "img/product/accessories/pendentNecklace-3.png",
        }
    },
    {    
        "id":20,
        "name": "Men minimalist fashion glasses",    
        "price": 5.90,    
        "description": "This item is a black, square-shaped accessory with a casual style. It is made from PC, which is a durable and lightweight material. The black color and square shape make this accessory versatile and easy to pair with a range of outfits. It can be used as a functional item or as a fashion accessory to add a stylish touch to any outfit. The material of the accessory is easy to clean and maintain, making it a practical addition to any wardrobe. Its sleek and simple design make it suitable for various occasions and outfits. WARNING: Fashion Glasses. Not to be worn outside to protect the eyes against strong sunlight. Not designed or intended for use in play by children.",
        "category":"accessories",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/fashionGlasses-6.png",
            2 : "img/product/accessories/fashionGlasses-7.png",
            3 : "img/product/accessories/fashionGlasses-8.png",
            4 : "img/product/accessories/fashionGlasses-9.png",
        }
    },
    {    
        "id":21,
        "name": "men metal buckle belt",    
        "price": 5.70,    
        "description": "This belt comes in a brown color and has a casual style. The belt is made from PU leather, which provides durability and a leather-like appearance. The belt is a PU buckle belt, meaning that it features a buckle made from the same material as the belt. The belt has a non-stretch material, which adds to its durability and sturdiness. The belt is suitable for casual wear and can be paired with a range of outfits to add a stylish touch. The brown color of the belt is versatile and can be worn with a range of colors. The material of the belt is easy to clean and maintain, making it a practical addition to any wardrobe.",
        "category":"accessories",
        "rating": 4,
        "label": 'sale',    
        "labelText": "Sale",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/belt-2.png",
            2 : "img/product/accessories/belt-1.png",
            3 : "img/product/accessories/belt.png",
        }
    },
    {    
        "id":22,
        "name": "men vintage minimalist round pointer pocket watch",    
        "price": 6.50,    
        "description": "This is a vintage-style pocket watch with a round shape. The case and strap of the watch are made of zinc alloy material. The watch dial color is white, and it has a Roman numeral scale display. The watch is not waterproof and is designed for men. The watch features other specular material, which is not specified in the description.",
        "category":"accessories",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/pocketWatch-1.png",
            2 : "img/product/accessories/pocketWatch-2.png",
            3 : "img/product/accessories/pocketWatch-3.png",
            4 : "img/product/accessories/pocketWatch-4.png",
        }
    },
    {    
        "id":23,
        "name": "1pair men round frame black fashion glasses",    
        "price": 5.00,    
        "description": "This is a casual item, likely to be an accessory, garment, or fashion item, that comes in a black color. The style of the item is casual, suggesting that it is meant to be comfortable and relaxed in appearance. The item has a round shape, which could describe a variety of things such as a bag, hat, or watch. More context would be needed to determine the exact nature of the item. WARNING: Fashion Glasses. Not to be worn outside to protect the eyes against strong sunlight. Not designed or intended for use in play by children",
        "category":"accessories",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/accessories/fashionGlasses-1.png",
            2 : "img/product/accessories/fashionGlasses-2.png",
            3 : "img/product/accessories/fashionGlasses-3.png",
            4 : "img/product/accessories/fashionGlasses-4.png",
        }
    },
    {    
        "id":24,
        "name": "faux suede faux peral decor ankle strap flats",    
        "price": 24.90,    
        "description": "This is an elegant ankle strap shoe with a point toe. The upper material of the shoe is made from suedette and comes in an apricot color. The strap type is an ankle strap, which adds to the shoe's overall elegance. The pattern type is plain, with no additional design elements beyond the strap and toe details. The shoe features pearls and metal as additional details, possibly as accents on the ankle strap or at the toe. The lining and insole materials are made from PU leather, which is known for its durability and comfort. The outsole material is made from rubber, which provides good traction and durability for the shoe.",
        "category":"women",
        "rating": 5,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":0,
        "images" : {
            1 : "img/product/womens/strapFlats-1.png",
            2 : "img/product/womens/strapFlats-2.png",
            3 : "img/product/womens/strapFlats-3.png",
            4 : "img/product/womens/strapFlats-4.png",
        }
    },
    {    
        "id":25,
        "name": "Appliques decor chunky heeled ankle strap sandals",    
        "price": 44.60,    
        "description": "This is a fashionable ankle strap shoe with an open toe design. The shoe comes in a pink color and features a plain pattern type, with no additional designs or patterns. The shoe has an ankle strap and chunky heels that measure a mid-heel height of 7.5cm/3inch. The upper material of the shoe is made from linen, which is a breathable and lightweight fabric. The shoe features appliques as additional details, possibly as decorative elements on the ankle strap or at the toe. The lining material is made from PU leather, known for its durability and comfort. The insole material is also made from linen, which provides good moisture-wicking properties. The outsole material is made from TPR, which is a durable and flexible material that provides good traction.",
        "category":"women",
        "rating": 5,
        "label": 'new',    
        "labelText": "New Release",
        "delivery": 4.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/womens/sandals-1.png",
            2 : "img/product/womens/sandals-2.png",
            3 : "img/product/womens/sandals-3.png",
            4 : "img/product/womens/sandals-4.png",
        }
    },
    {    
        "id":26,
        "name": "men slant pocket drawstring waist pants",    
        "price": 27.49,    
        "description": "These are casual jogger pants that come in a dusty blue color with a plain pattern type. The pants feature a drawstring waist closure and have a natural waistline. The length of the pants is cropped, suggesting that they may end just above the ankle. The pants have a regular fit and are made from a non-stretch woven fabric that is composed of 100% polyester. There is a drawstring detail and pocket detail on the pants, which add to their casual style. The pants are unlined and not sheer, meaning that they will not be see-through when worn. The care instructions for these pants suggest that they can be machine washed or professionally dry cleaned.",
        "category":"men",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/mens/pants-4.png",
            2 : "img/product/mens/pants-5.png",
            3 : "img/product/mens/pants-6.png",
        }
    },
    {    
        "id":27,
        "name": "men letter graphic drawstring cargo pants",    
        "price": 25.99,    
        "description": "These are street-style cargo pants that come in a black color with a letter pattern type. The pants feature a drawstring waist closure and have a natural waistline. The length of the pants is long, suggesting that they may extend down to the ankles or beyond. The pants have a loose fit and are made from a non-stretch fabric that is composed of 100% polyester. There is a drawstring detail and pocket detail on the pants, which add to their cargo-style. The pants are unlined and not sheer, meaning that they will not be see-through when worn. The care instructions for these pants suggest that they can be machine washed or professionally dry cleaned.",
        "category":"men",
        "rating": 4,
        "label": 'sale',    
        "labelText": "Sale",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/mens/pants-2.png",
            2 : "img/product/mens/pants-1.png",
            3 : "img/product/mens/pants-3.png",
        }
    },
    {    
        "id":28,
        "name": "men colorblock block lace-up front knit sneakers running shoes",    
        "price": 38.99,    
        "description": "These shoes come in black color and are true to size fit. The shoes feature a lace-up strap type and have a colorblock and letter pattern type on the upper material, which gives them a stylish look. The upper material of the shoes is made from fabric, while the lining and insole materials are made from mesh, which provides good breathability and comfort. The outsole material is made from TPU, which is a durable and flexible material that provides good traction.",
        "category":"men",
        "rating": 5,
        "label": 'new',    
        "labelText": "New",
        "delivery": 3.95,
        "newcollection":1,
        "images" : {
            1 : "img/product/mens/shoes.png",
            2 : "img/product/mens/shoes-1.png",
            3 : "img/product/mens/shoes-2.png",
            4 : "img/product/mens/shoes-3.png",
        }
    },
    {    
        "id":29,
        "name": "women square toe t-strap flats",    
        "price": 38.99,    
        "description": "These t-strap flats are designed with a square toe shape and a slip-on fastening and back detail. The upper material of these flats is made from synthetic material, while the sole material is made from PVC, providing durability and comfort. These flats have a cushioned footbed, which provides extra comfort for your feet. The outsole is textured and patterned, which helps to provide good grip and traction when walking. The heel height of these flats is 2.54 cm, which provides a comfortable and practical height for everyday wear. These flats are suitable for casual occasions and have a solid pattern. The ankle height is regular, providing a comfortable fit around the ankle. To clean these flats, it is recommended to wipe them with a clean dry cloth to remove any dust.",
        "category":"women",
        "rating": 4,
        "label": 'sale',    
        "labelText": "Sale",
        "delivery": "Free Delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/womens/flats-1.png",
            2 : "img/product/womens/flats-2.png",
            3 : "img/product/womens/flats-3.png",
            4 : "img/product/womens/flats-5.png",
        }
    },
    {    
        "id":30,
        "name": "6 Matte Lipstick with 6 Lipliners Durable Lip Gloss Waterproof High Pigmented Velvet Lipgloss Kit Beauty Cosmetics Makeup Gift for Girls",    
        "price": 10.70,    
        "description": `This is a Langmanni brand liquid lipstick in the color red. It has a matte finish and is designed to be long-lasting, moisturizing, and waterproof. The product comes in a tube package and is suitable for all skin tones, targeting girls as the intended audience. This kit contains 6 matte lipsticks and 6 corresponding lipliners in nude shades. The lipstick formula includes moisturizing ingredients to keep lips feeling relaxed, emollient and silky without drying them out. It long-lasting, non-sticky, and would not fade when touched or exposed to water, making it kiss-proof and able to stay on for up to 12 hours. The kit comes in a gift box, making it a great choice for occasions such as Halloween, Christmas, Valentine Day, birthdays, weddings, dance parties, cosmetic shows, and graduations. The lipsticks come in beautiful colors and have an interesting appearance.`,
        "category":"cosmetic",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": "Free Delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/eyeLiner1.jpg",
            2 : "img/product/cosmetics/eyeLiner2.jpg",
            3 : "img/product/cosmetics/eyeLiner3.jpg",
            4 : "img/product/cosmetics/eyeLiner4.jpg",
            5 : "img/product/cosmetics/eyeLiner5.jpg",
        }
    },
    {    
        "id":31,
        "name": "Retro Eyeshadow Palette",    
        "price": 29.70,    
        "description": "This is a must-have eyeshadow palette with 15 romantic burgundy and mauve shades combined with gray-browns, taupes, dusty roses, and vintage pinks. The shades provide maximum color payoff with minimal effort and blend seamlessly to achieve vibrant, ultra-pigmented, long-lasting looks. The palette is free of parabens, phthalates, and mineral oil, and is cruelty-free and comes in recyclable packaging. The shades and formulas were hand-designed by world-renowned makeup artist Natasha Denona, and are made with high-quality pure color pigments, chroma crystals, and mineral pearls. The buttery-smooth, hydrating eyeshadow formula wears beautifully on any skin type and skin tone. The palette contains 15 eyeshadows and is 15 x 0.65 oz/ 19.25 g in size.",
        "category":"cosmetic",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": "Free Delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/eyeShadow-1.png",
            2 : "img/product/cosmetics/eyeShadow-2.png",
            3 : "img/product/cosmetics/eyeShadow-3.png",
            4 : "img/product/cosmetics/eyeShadow-4.png",
            5 : "img/product/cosmetics/eyeShadow-5.png",
            6 : "img/product/cosmetics/eyeShadow-6.png",
        }
    },
    {    
        "id":32,
        "name": "Pinkflash 18-Color Matte Lipstick Matte Long-Lasting Waterproof Velvet Lip Glaze Tint Lip Gloss Kit Women Cosmetics Makeup Tools",    
        "price": 10.70,    
        "description": "This is an 18-color matte lipstick set that provides long-lasting and waterproof wear. The velvet lip glaze tint formula creates a smooth and soft texture on the lips. The kit includes a variety of shades to choose from, making it suitable for any occasion. It is a great addition to any woman cosmetics collection and makeup tools.",
        "category":"cosmetic",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": "Free Delivery",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/waterproofLipstick.jpeg",
            2 : "img/product/cosmetics/waterproofLipstick-1.jpeg",
            3 : "img/product/cosmetics/waterproofLipstick-2.jpeg",
            4 : "img/product/cosmetics/waterproofLipstick-3.jpeg",
            5 : "img/product/cosmetics/waterproofLipstick-4.jpeg",
            6 : "img/product/cosmetics/waterproofLipstick-5.jpeg",
        }
    },
    {    
        "id":33,
        "name": "12 Mystery Mac Pigment Eyeshadow Makeup Cosmetic Sampler Gift Lot Clear Case Set",    
        "price": 15.70,    
        "description": "This seller is a 5-star mystery box seller and is offering a new set of 12 concentrated loose MAC pigments. The pigments are suitable for use on the eyes and lips and come in 1/4 tsp quantities placed in sterile clear cosmetic jars. The seller is open to requests for specific colors, such as blue, silver, grey, green, warm colors, or specific names, and will include them if possible. The set may include colors such as Vanilla, Tan, Melon, Naked, Rose, Teal, Violet, Copper Sparkle, Romp, Pink Opal, Jest, etc. The pigments come in both shimmer and matte finishes and come in a clear carrying case. Each pot of pigment could last for years due to its high pigment concentration, requiring only a small amount for normal application.",
        "category":"cosmetic",
        "rating": 4,
        "label": '',    
        "labelText": "",
        "delivery": "5.00",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/eyeShadow-pigment-1.png",
            2 : "img/product/cosmetics/eyeShadow-pigment-2.png",
            3 : "img/product/cosmetics/eyeShadow-pigment-3.png",
            4 : "img/product/cosmetics/eyeShadow-pigment-4.png",
        }
    },
    {    
        "id":34,
        "name": "E.L.F. Glitter eye liner shimmering gold",    
        "price": 6,    
        "description": "This unopened box contains a Shimmering Gold Gel Glitter Eye Liner that can transform your regular eyeliner into a metallic finish. It is perfect for layering over eyeliner for a dramatic effect or can be worn alone for a sheer wash of glitter color. The superfine glitter formula adds a touch of glamour to your eye makeup. Two versions of the product are available with slightly different boxes, and the buyer will receive a random choice unless they specify their preference. The product comes from a pet and smoke-free home.",
        "category":"cosmetic",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": "4.99",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/glitter-eyeLiner-1.png",
            2 : "img/product/cosmetics/glitter-eyeLiner-2.png",
            3 : "img/product/cosmetics/glitter-eyeLiner-3.png",
            4 : "img/product/cosmetics/glitter-eyeLiner-4.png",
            5 : "img/product/cosmetics/glitter-eyeLiner-5.png",
        }
    },
    {    
        "id":35,
        "name": "L’ORÉAL Age Perfect Foundation 100 Toffee",    
        "price": 25.90,    
        "description": "L’ORÉAL Age Perfect Foundation 100 Toffee is a foundation specially formulated for mature and sensitive skin. It provides coverage while caring for the skin, with a formula that is designed to not settle into fine lines or wrinkles. Toffee is the shade name, indicating a medium-deep tone with warm undertones.",
        "category":"cosmetic",
        "rating": 3,
        "label": '',    
        "labelText": "",
        "delivery": "4.99",
        "newcollection":0,
        "images" : {
            1 : "img/product/cosmetics/foundation-1.png",
            2 : "img/product/cosmetics/foundation-2.png",
            3 : "img/product/cosmetics/foundation-3.png",
        }
    }

];

var categories = [  
    {    
        "id":"men",
        "name": "Men's",    
        "description": "This is the description for product 1",
        "image" : "img/banner/5.jpeg",
        "rating": 3,
        "label": 'new', 
        "banner" : [
            "men jacket",
              'men hat',
              'men belt' 
        ]
},  
    {    
        "id":'women',
        "name": "Women's",    
        "description": "This is the description for product 2",
        "image" : "img/banner/2.jpg",
        "rating": 4,  
        "label": 'stockout',  
        "banner" : {
            0 : "Luminous Lace",
            1 : 'Casual Couture',
            2 : 'Urban Chic' 
        }    
    },
    {    
        "id":'kids',
        "name": "kid's",    
        "description": "This is the description for product 2",
        "image" : "img/banner/9.jpeg",
        "rating": 4,  
        "label": 'stockout',  
        "banner" : {
            0 : "Tiny Treasures",
            1 : 'Girls Buckle Decor Flats',
            2 : 'Floral Print Pants' 
        }    
    },
    {    
        "id":'cosmetic',
        "name": "cosmetic",    
        "description": "This is the description for product 2",
        "image" : "img/banner/7.jpeg",
        "rating": 4,  
        "label": 'stockout',  
        "banner" : {
            0 : "jacket",
            1 : 'hat',
            2 : 'belt' 
        }    
    },
    {    
        "id":'accessories',
        "name": "accessories",    
        "description": "This is the description for product 2",
        "image" : "img/banner/8.jpeg",
        "rating": 4,  
        "label": 'stockout',  
        "banner" : {
            0 : "Leather Structured Handheld Bag",
            1 : 'black fashion glasses',
            2 : 'Solid Leather Handheld' 
        }    
    }
];